-- menus tablosundaki page_description alanlarının sayfa içeriklerine göre doldurulması
-- Güncellemeler id bazlı yapılır; aynı menu_link birden fazla kayıtta bulunabilir.

UPDATE `menus` SET `page_description` = 'Genel sistem özeti, istatistikler ve hızlı erişim widgetları' WHERE `id` = 1;
UPDATE `menus` SET `page_description` = 'Personel kayıtları, puantaj ve performans işlemleri' WHERE `id` = 2;
UPDATE `menus` SET `page_description` = 'Personel iş performansı ve çalışma verimlilik raporları' WHERE `id` = 3;
UPDATE `menus` SET `page_description` = 'Tüm personel listesi, özlük bilgileri ve kart yönetimi' WHERE `id` = 4;
UPDATE `menus` SET `page_description` = 'Saha iş takip, raporlama ve kaçak kontrol işlemleri' WHERE `id` = 5;
UPDATE `menus` SET `page_description` = 'Aylık maaş bordrosu, hesaplama ve raporlama işlemleri' WHERE `id` = 6;
UPDATE `menus` SET `page_description` = 'Gelen ve giden evrak kayıtlarının takibi' WHERE `id` = 7;
UPDATE `menus` SET `page_description` = 'Şube kayıtlarının listelenmesi ve yönetimi' WHERE `id` = 8;
UPDATE `menus` SET `page_description` = 'Nöbet planlama, talep ve onay işlemleri' WHERE `id` = 9;
UPDATE `menus` SET `page_description` = 'Personel nöbet çizelgesi planlama ve takvim görünümü' WHERE `id` = 10;
UPDATE `menus` SET `page_description` = 'Personelin günlük konum ve çalışma durumu takibi' WHERE `id` = 11;
UPDATE `menus` SET `page_description` = 'Kasa, gelir-gider ve hesap hareketleri yönetimi' WHERE `id` = 12;
UPDATE `menus` SET `page_description` = 'Gelir ve gider kayıtlarının listelenmesi' WHERE `id` = 13;
UPDATE `menus` SET `page_description` = 'Kasa hareketleri ve güncel bakiye takibi' WHERE `id` = 14;
UPDATE `menus` SET `page_description` = 'Personel puantaj, mesai ve izin takip ekranı' WHERE `id` = 15;
UPDATE `menus` SET `page_description` = 'Kayıtlı evrakların listelenmesi ve arşivi' WHERE `id` = 16;
UPDATE `menus` SET `page_description` = 'Yeni giden evrak kaydı oluşturma' WHERE `id` = 17;
UPDATE `menus` SET `page_description` = 'Yeni gelen evrak kaydı oluşturma' WHERE `id` = 18;
UPDATE `menus` SET `page_description` = 'Kullanıcı hesapları ve yetki grubu yönetimi' WHERE `id` = 19;
UPDATE `menus` SET `page_description` = 'Sistem kullanıcıları, erişim ve hesap bilgileri' WHERE `id` = 20;
UPDATE `menus` SET `page_description` = 'Kullanıcı rolleri ve modül bazlı yetkilendirme ayarları' WHERE `id` = 21;
UPDATE `menus` SET `page_description` = 'Demirbaş envanteri, depo ve personel zimmet takibi' WHERE `id` = 22;
UPDATE `menus` SET `page_description` = 'Sistem geneli tanım ve parametre kayıtları' WHERE `id` = 23;
UPDATE `menus` SET `page_description` = 'Gelir ve gider türlerinin tanımlanması' WHERE `id` = 24;
UPDATE `menus` SET `page_description` = 'Mail, SMS ve anlık bildirim gönderim işlemleri' WHERE `id` = 25;
UPDATE `menus` SET `page_description` = 'Personele toplu veya bireysel SMS gönderimi' WHERE `id` = 26;
UPDATE `menus` SET `page_description` = 'Personele toplu veya bireysel e-posta gönderimi' WHERE `id` = 27;
UPDATE `menus` SET `page_description` = 'Kurum içi telefon ve iletişim rehberi' WHERE `id` = 28;
UPDATE `menus` SET `page_description` = 'Sistem yapılandırması ve firma ayarları' WHERE `id` = 29;
UPDATE `menus` SET `page_description` = 'Site ana sayfa slider görsellerinin yönetimi' WHERE `id` = 30;
UPDATE `menus` SET `page_description` = 'Yeni slider görseli ekleme ve düzenleme' WHERE `id` = 31;
UPDATE `menus` SET `page_description` = 'Kayıtlı slider görsellerinin listesi' WHERE `id` = 32;
UPDATE `menus` SET `page_description` = 'Site yönetim kadrosu içerik alanı' WHERE `id` = 33;
UPDATE `menus` SET `page_description` = 'Yeni yönetim kadrosu kaydı ekleme' WHERE `id` = 34;
UPDATE `menus` SET `page_description` = 'Yönetim kadrosu kayıtlarının listesi' WHERE `id` = 35;
UPDATE `menus` SET `page_description` = 'Kurumsal hakkımızda sayfası içerik düzenleme' WHERE `id` = 36;
UPDATE `menus` SET `page_description` = 'Site haber ve duyuru içeriklerinin yönetimi' WHERE `id` = 37;
UPDATE `menus` SET `page_description` = 'Yeni haber veya duyuru ekleme' WHERE `id` = 38;
UPDATE `menus` SET `page_description` = 'Haber ve duyuru kayıtlarının listesi' WHERE `id` = 39;
UPDATE `menus` SET `page_description` = 'Site sık sorulan sorular içerik yönetimi' WHERE `id` = 40;
UPDATE `menus` SET `page_description` = 'Yeni sık sorulan soru ekleme' WHERE `id` = 41;
UPDATE `menus` SET `page_description` = 'Sık sorulan soru kayıtlarının listesi' WHERE `id` = 42;
UPDATE `menus` SET `page_description` = 'Temsilcilik başvuru ve talep kayıtları' WHERE `id` = 43;
UPDATE `menus` SET `page_description` = 'Banka online hesap hareketlerinin izlenmesi' WHERE `id` = 46;
UPDATE `menus` SET `page_description` = 'Saha ekip kodlarının tanımlanması' WHERE `id` = 47;
UPDATE `menus` SET `page_description` = 'Aylık bordro hesaplama ve tahakkuk işlemleri' WHERE `id` = 48;
UPDATE `menus` SET `page_description` = 'Bordro hesaplama parametreleri ve yasal oranlar' WHERE `id` = 49;
UPDATE `menus` SET `page_description` = 'Personel izin, avans ve diğer talep işlemleri' WHERE `id` = 50;
UPDATE `menus` SET `page_description` = 'İş türü ve kategori tanımlamaları' WHERE `id` = 51;
UPDATE `menus` SET `page_description` = 'Mail, SMS ve bildirim gönderim raporları' WHERE `id` = 55;
UPDATE `menus` SET `page_description` = 'Araç puantaj, yakıt ve performans yönetimi' WHERE `id` = 56;
UPDATE `menus` SET `page_description` = 'Uygulama içi anlık bildirim gönderimi' WHERE `id` = 57;
UPDATE `menus` SET `page_description` = 'Personel izin türlerinin tanımlanması' WHERE `id` = 58;
UPDATE `menus` SET `page_description` = 'Puantaj Excel dosyası yükleme ve içe aktarma' WHERE `id` = 59;
UPDATE `menus` SET `page_description` = 'Bordro banka, kesinti ve vergi raporları' WHERE `id` = 60;
UPDATE `menus` SET `page_description` = 'İş takip özet raporları ve istatistikleri' WHERE `id` = 61;
UPDATE `menus` SET `page_description` = 'Endeks okuma ve iş listesi detay raporları' WHERE `id` = 62;
UPDATE `menus` SET `page_description` = 'Nöbet değişim ve nöbet izin talepleri' WHERE `id` = 63;
UPDATE `menus` SET `page_description` = 'Defter bazında okuma ve abone durum raporu' WHERE `id` = 67;
UPDATE `menus` SET `page_description` = 'Atanan görevler ve sistem bildirimleri özeti' WHERE `id` = 69;
UPDATE `menus` SET `page_description` = 'Şirket ve personel araçlarının takip ve yönetimi' WHERE `id` = 70;
UPDATE `menus` SET `page_description` = 'Araç günlük kullanım ve puantaj kayıtları' WHERE `id` = 71;
UPDATE `menus` SET `page_description` = 'Firma sözleşme kayıtları ve detayları' WHERE `id` = 76;
UPDATE `menus` SET `page_description` = 'Firma hakediş hesaplama ve sözleşme yönetimi' WHERE `id` = 80;
UPDATE `menus` SET `page_description` = 'Kurum içi duyuru ve etkinlik paylaşımları' WHERE `id` = 81;
UPDATE `menus` SET `page_description` = 'Demirbaş kategorilerinin tanımlanması' WHERE `id` = 82;
UPDATE `menus` SET `page_description` = 'Unvan ve unvan bazlı ücret tanımlamaları' WHERE `id` = 83;
UPDATE `menus` SET `page_description` = 'Defter kodu ve bölge tanımlamaları' WHERE `id` = 84;
UPDATE `menus` SET `page_description` = 'Toplu rapor oluşturma ve dışa aktarma işlemleri' WHERE `id` = 85;
UPDATE `menus` SET `page_description` = 'Personel görev atama ve not takibi' WHERE `id` = 86;
UPDATE `menus` SET `page_description` = 'İcra dairesi bilgilerinin tanımlanması' WHERE `id` = 87;
UPDATE `menus` SET `page_description` = 'Personel bordro kesintilerinin listesi' WHERE `id` = 610;
UPDATE `menus` SET `page_description` = 'Bordro banka ödeme listesi ve dışa aktarımı' WHERE `id` = 611;
UPDATE `menus` SET `page_description` = 'Araç yakıt tüketimi ve kilometre performans analizi' WHERE `id` = 915;
UPDATE `menus` SET `page_description` = 'İş ve personel bazlı maliyet analiz raporları' WHERE `id` = 916;
UPDATE `menus` SET `page_description` = 'Finansal gelir ve gider hareketlerinin takibi' WHERE `id` = 917;
UPDATE `menus` SET `page_description` = 'Cari hesap kartları ve bakiye takibi' WHERE `id` = 918;
UPDATE `menus` SET `page_description` = 'Cari hesap borç, alacak ve bakiye hareketleri' WHERE `id` = 919;
UPDATE `menus` SET `page_description` = 'Online kesme/açma, endeks ve sayaç sorgulama' WHERE `id` = 920;
UPDATE `menus` SET `page_description` = 'Nöbet kayıtlarının onay ve kontrol işlemleri' WHERE `id` = 921;
UPDATE `menus` SET `page_description` = 'Form ve tutanak şablonlarının yönetimi' WHERE `id` = 922;
UPDATE `menus` SET `page_description` = 'Kullanıcılardan gelen destek taleplerinin yönetimi' WHERE `id` = 929;
UPDATE `menus` SET `page_description` = 'Oluşturduğunuz destek taleplerinin takibi' WHERE `id` = 931;
UPDATE `menus` SET `page_description` = 'Demirbaş kayıtları ve envanter listesi' WHERE `id` = 934;
UPDATE `menus` SET `page_description` = 'Sayaç stok ve depo hareket takibi' WHERE `id` = 935;
UPDATE `menus` SET `page_description` = 'Aparat stok ve depo hareket takibi' WHERE `id` = 936;
UPDATE `menus` SET `page_description` = 'Demirbaş servis ve arıza kayıtları' WHERE `id` = 937;
UPDATE `menus` SET `page_description` = 'Personel demirbaş zimmet ve iade kayıtları' WHERE `id` = 938;
UPDATE `menus` SET `page_description` = 'Demirbaş, stok ve zimmet raporları' WHERE `id` = 939;
UPDATE `menus` SET `page_description` = 'Araç kilometre bildirimlerinin onay işlemleri' WHERE `id` = 941;
UPDATE `menus` SET `page_description` = 'Riskli personel ve şüpheli işlem raporu' WHERE `id` = 944;
UPDATE `menus` SET `page_description` = 'Saha ihbar bildirimleri, trend ve takip yönetimi' WHERE `id` = 945;
UPDATE `menus` SET `page_description` = 'Saha kaçak kontrol tespit ve tutanak takibi' WHERE `id` = 954;
